### ISSUE TITLE
TODO list for project

### ISSUE THREAD

**Issue by GuitarmonYz** [proton1030/NosyAspiration#1]
#### General
- [x] Setup project files and design prototype project structure 

#### Articulatory Speech Synthesis
- [x] Analysis Javascript code of https://dood.al/pinktrombone/
- [x] Read paper http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.142.5360&rep=rep1&type=pdf (glottis souce modeling)
- [x] Translate Glottis model into cpp class
   - [x] interface and class design
   - [x] decouple glottal source and glottis interface
   - [x] test glottal source generation
   - [x] test glottis model by changing parameters in code
   - [x] connect user interface with Glottis API
- [x] Translate Tract model into cpp class
- [x] Integrate Glottis and Tract model, test with given frequency
- [ ] Implement Macro Editor controls, which enables pronouncing syllables in sequences with timing controls

#### GUI design and implementation
- [ ] Design meta-parameters for higher hierarchical controls over the sound

#### Real-time pitch tracker
- [x] implement real-time ACF pitch tracker in cpp

**Comment by proton1030** [comment]
## Challenges

- [ ] Finding the mapping between a specific speaker's voice timbre and th Glottis model's parameters
- [x] Robust real-time pitch tracking algorithm implementation 
- [ ] Expressive GUI controls which allows intuitive controlling to visualize the generated syllables

**Comment by GuitarmonYz** [comment]
Wait for possible future work
