### ISSUE TITLE
Final To-do List

### ISSUE THREAD

**Issue by proton1030** [proton1030/NosyAspiration#4]
Top priorities:
- [x] GUI Implementation
- [ ] Test cases (cross-platform compiling, memory leakages)

Lower priorties:
- [x] Correlate frequency changing speed to frequency difference
- [x] Volume non-linear attenuation according to RMS
- [x] Make Vibrato parameter adjustable (present on GUI as a knob)
- [x] Adjustable post-FX gain control
